### ISSUE TITLE
POST Operation - Foreign Key connection of entities

### ISSUE THREAD

**Issue by rickertmar** [rickertmar/KinoticketSystem#14]
LocationAddress Objekt in der DB nicht über den Key gelinkt (in cinema table location_address_id = null)

API Implementierung für LocationAddress muss noch erstellt werden (Controller, Service, etc.), sodass LocationAddress korrekt erstellt werden kann bevor es in der Cinema Erstellung verwendet wird

**Comment by rickertmar** [comment]
Ich bekomme diesen Fehler: "java.sql.SQLException: Field 'id' doesn't have a default value"

Ich denke es könnte dasselbse Problem wie hier sein: [https://stackoverflow.com/questions/804514/hibernate-field-id-doesnt-have-a-default-value]

**Comment by K-Lorenz** [comment]
Kann sein, dass es daran liegt.

> LocationAddress Objekt in der DB nicht über den Key gelinkt (in cinema table location_address_id = null)
> 
> API Implementierung für LocationAddress muss noch erstellt werden (Controller, Service, etc.), sodass LocationAddress korrekt erstellt werden kann bevor es in der Cinema Erstellung verwendet wird

Du kannst auch mal probieren, den SQL update modus zu ändern in: application.properties. Bei dem Hibernateddl ding oder wie das heißt gibt es eine Einstellung, die heißt create-drop vielleicht wird dann die DB ordentlich neugeladen

**Comment by rickertmar** [comment]
Ich habe den value auf create-drop gesetzt, dann kommt beim starten diese Meldung (die hab ich auch beim Versuch den Location Address table manuell zu droppen schon bekommen):

org.hibernate.tool.schema.spi.CommandAcceptanceException: Error executing DDL "drop table if exists location_address" via JDBC [Cannot drop table 'location_address' referenced by a foreign key constraint 'FK278wwybxhjrxplh0i6uj646js' on table 'user'

Ich will dir da jetzt nicht bei user reinpfuschen....weißt du was das mit diesem foreign key constraint auf sich hat?
(der LocationAddressAPI branch ist aktuell)

**Comment by K-Lorenz** [comment]
Ne alles gut kannst da schon was verändern. Kann sein dass das ein alter Key ist. Lösch ihn eif manuel. Musst halt bisschen in der Tabelle rumsuchen. Aber wenn create-drop den auch Löschen will kannst du das eigtl sicher machen.

**Comment by rickertmar** [comment]
alles was ich in der db droppe wird ja neugeneriert oder? 
Weil ich gerade bei fast alle tabellen die meldung von oben bekomme jeweils mit unterschiedlichen foreign keys

**Comment by K-Lorenz** [comment]
ja wird alles neugeneriert. Aber iwas stinkt hier...
probiers eif aus

**Comment by rickertmar** [comment]
@K-Lorenz du hast ja schon ein paar User zum Test erstellt....bei dir klappt die relation zu LocationAddress auch nicht...hast du eine Vermutung woran das liegt?
<img width="726" alt="image" src="https://github.com/rickertmar/KinoticketSystem/assets/115364452/7d45d3d5-d0e7-4a42-bf56-f0b47bdc5b84">

**Comment by K-Lorenz** [comment]
hab keine Adresse eingegeben. Konnte übrrs WE nix machen. Bin wie gesagt noch an der Authentifizierung dran.
