### ISSUE TITLE
Test Setup: Database for testing

### ISSUE THREAD

**Issue by rickertmar** [rickertmar/KinoticketSystem#30]
@K-Lorenz  Meinung zu einer Datenbank fürs Testing?

Geht das auch über unsere MySQL DB, sodass das Testing auf einer cleanen DB laufen kann, die jedes Mal nach den Tests komplett droppt?

Alternativ würde ich das mit einer in-memory H2 db machen....die bräuchte dann kein extra DB-Server

**Comment by K-Lorenz** [comment]
Frag mal Louis ob er was weiß. Bin ehrlich schlecht informiert

**Comment by lrau22** [comment]
Geht in der Theorie mit einer MySQL in unsrer Azure Cloud. Ich hab halt wenig Ahnung von Azure. Ob und wie das mit In-Memory DBs geht, davon hab ich auch keine Ahnung.

**Comment by rickertmar** [comment]
Ich setze mich mal mehr mit den in-memory dbs auseinander bzw. gucke inwiefern wir die brauchen, wenn wir mockito benutzen
