### ISSUE TITLE
Problem with data type LocalDateTime

### ISSUE THREAD

**Issue by rickertmar** [rickertmar/KinoticketSystem#52]
Showing Controller Test throws:

> com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Java 8 date/time type `java.time.LocalDateTime` not supported by default: add Module "com.fasterxml.jackson.datatype:jackson-datatype-jsr310" to enable handling (through reference chain: com.dhbw.kinoticket.request.CreateShowingRequest["time"])

Even after adding the dependency, it does not resolve the testing error.

(Removed LocalDateTime test parameter for now)

**Comment by K-Lorenz** [comment]
Seems like a Jackson error. Did you try to add the dependency?

**Comment by rickertmar** [comment]
Of course. Also tried @AutoConfigureJsonTesters and inner config class for adding localdatetime to objectmapper.

**Comment by K-Lorenz** [comment]
Is it a missing maven dependency? I dont get your error...

**Comment by rickertmar** [comment]
Tried it, but no. Error does not get thrown anymore, because i removed the throwing test parameter. `request.setTime(LocalDateTime.now())`

> (Removed LocalDateTime test parameter for now)

**Comment by rickertmar** [comment]
Anyway, as long as the logic works, that shouldn't be a problem.
